### ISSUE TITLE
File > Open > Hypar function directory is ambiguous

### ISSUE THREAD

**Issue by anthonyhauck** [hypar-io/FunctionBuilder#8]
Open Folder ?

![image](https://user-images.githubusercontent.com/33582525/64652766-a11ba280-d3f2-11e9-9f60-c8740fc408d9.png)

![image](https://user-images.githubusercontent.com/33582525/64653010-420a5d80-d3f3-11e9-908a-706fd3f38a91.png)

**Comment by ikeough** [comment]
Which version of VS Code are you using? Version 1.38.0 has `File -> Open...`.

**Comment by ikeough** [comment]
I think this can be improved to:
>- File > Open... > Select the directory you created in the first step, or an existing Hypar function directory (a directory with a `hypar.json` file).

**Comment by anthonyhauck** [comment]
Wouldn't that be File > Open Folder.. ?

![image](https://user-images.githubusercontent.com/33582525/64729240-c5d35100-d4aa-11e9-8585-66f4a7650e6b.png)

Version: 1.38.0 (system setup)
Commit: 3db7e09f3b61f915d03bbfa58e258d6eee843f35
Date: 2019-09-03T21:49:13.459Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763

**Comment by ikeough** [comment]
My point is that my version of VS Code has a different file menu:
![image](https://user-images.githubusercontent.com/1139788/64739974-a0ddde80-d4a8-11e9-8d82-a45578aaaf6c.png)

**Comment by anthonyhauck** [comment]
...which I was wondering about. I thought the whole premise of this environment was that it was exactly the same on all OSes?
